name: theraman
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.2
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  auto_route: ^7.8.3
  talker_flutter: ^3.3.1
  auto_size_text: ^3.0.0
  dio: ^5.3.3
  fluttertoast: ^8.2.2
  talker_dio_logger: ^2.3.0
  dio_smart_retry: ^5.0.0
  multiple_result: ^5.1.0
  pin_code_text_field: ^1.8.0
  alt_sms_autofill: ^1.0.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.0.0
  flutter_native_splash: ^2.3.3
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
